Simplifying image names and hippocampus surface generation.
NIST-MNI/nist_mni_pipelines pull request #5
Opened 2020-12-14 16:58 UTC by rphellan

Simplifying image names to make them more understable.
Adding hippocampus surface generation option.

2020-12-15 15:22 UTC, vfonov requested changes
See my comments to the code

2020-12-15 15:22 UTC, vfonov commented on ipl/lp/pipeline.py
> +                                            library_description='/data/ipl/scratch08/vfonov/adni_jens/jens_hc_lib_20170621/library.json',
`/data/ipl/scratch08/vfonov/adni_jens/jens_hc_lib_20170621` - refers to internal BIC path, you should specify location of the library as parameter
also, library_description should be a dictionary, to load from json:
`json.load(open('.......json'))`

2020-12-15 15:22 UTC, vfonov commented on ipl/lp/pipeline.py
> +                                            parameters='/data/ipl/scratch08/vfonov/adni_jens/jens_hc_segment_20170621.json',
parameters should be dictionary too

2020-12-15 15:22 UTC, vfonov commented on ipl/segment/fuse.py
> +                    library_description={},
This change will break other modules that call fusion_segment

2020-12-15 15:22 UTC, vfonov commented on ipl/lp/pipeline.py
> +            t1w_tal_noscale=MriScan(prefix=tal_dir, name=dataset_id+'_full_head_image',modality='t1w')
This change breaks compatibility with other pipeline outputs

2020-12-17 21:04 UTC, rphellan commented
I will just close this pull request as I am working on the IBIS branch. The changes can be ignored.

2020-12-17 21:12 UTC, closed without merging